AllCops:
  Exclude:
    - db/schema.rb
    - vendor/**/*
  DisplayCopNames: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Max: 40
